### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by ghost** [The-Sickness/S6-MM#9]
Sorry for being so annoying, but after I start compiling the kernel I get this error
-------------------------------------------------------------------------------------------------------------------
  LD      drivers/video/exynos/decon/vpp/built-in.o
  CC      drivers/video/exynos/decon/decon_reg_7420.o
  LD      drivers/watchdog/watchdog.o
  LD      drivers/watchdog/built-in.o
  CC      drivers/video/exynos/decon/panels/s6e3ha2_s6e3ha0_wqhd_lcd_ctrl.o
  CC      drivers/video/exynos/decon/panels/dsim_backlight.o
drivers/video/exynos/decon/panels/dsim_backlight.c: In function 'dsim_panel_get_elvssoffset':
drivers/video/exynos/decon/panels/dsim_backlight.c:132:65: error: 'struct panel_private' has no member named 'ldu_correction_state'
scripts/Makefile.build:308: recipe for target 'drivers/video/exynos/decon/panels/dsim_backlight.o' failed
make[5]: *** [drivers/video/exynos/decon/panels/dsim_backlight.o] Error 1
make[5]: *** Waiting for unfinished jobs....
  CC      net/netfilter/xt_policy.o
  CC      net/netfilter/xt_qtaguid_print.o
  CC      net/netfilter/xt_qtaguid.o
  LD      drivers/usb/misc/built-in.o
  CC      net/netfilter/xt_quota.o
  CC      net/sched/sch_blackhole.o
  CC      drivers/usb/gadget/usbstring.o
  CC      net/sched/cls_api.o
scripts/Makefile.build:455: recipe for target 'drivers/video/exynos/decon/panels' failed
make[4]: *** [drivers/video/exynos/decon/panels] Error 2
make[4]: *** Waiting for unfinished jobs....
  CC      net/sched/act_api.o
  LD      drivers/video/exynos/panels/built-in.o
  CC      net/sched/act_police.o
  CC      drivers/usb/host/xhci-mem.o
  CC      drivers/usb/gadget/config.o
  CC      net/netfilter/xt_quota2.o
  CC      net/sched/act_gact.o
scripts/Makefile.build:455: recipe for target 'drivers/video/exynos/decon' failed
make[3]: *** [drivers/video/exynos/decon] Error 2
scripts/Makefile.build:455: recipe for target 'drivers/video/exynos' failed
make[2]: *** [drivers/video/exynos] Error 2
scripts/Makefile.build:455: recipe for target 'drivers/video' failed
make[1]: *** [drivers/video] Error 2
make[1]: *** Waiting for unfinished jobs....
  CC      drivers/usb/gadget/epautoconf.o
  CC      net/sched/act_mirred.o
  CC      net/sched/sch_fifo.o
  CC      net/sched/sch_htb.o
  CC      drivers/usb/gadget/composite.o
  CC      net/sched/sch_ingress.o
  CC      net/netfilter/xt_sctp.o
  CC      net/sched/sch_prio.o
  CC      net/sched/cls_u32.o
  CC      net/sched/cls_basic.o
  CC      net/sched/ematch.o
  CC      net/netfilter/xt_socket.o
  CC      drivers/usb/host/xhci-ring.o
  CC      net/netfilter/xt_state.o
  CC      net/sched/em_u32.o
  CC      net/netfilter/xt_statistic.o
  CC      net/netfilter/xt_string.o
  CC      drivers/usb/gadget/functions.o
  CC      net/netfilter/xt_time.o
  CC      drivers/usb/notify/host_notify_class.o
  CC      drivers/usb/phy/phy.o
  CC      net/netfilter/xt_u32.o
  LD      net/sched/built-in.o
  CC      drivers/usb/serial/usb-serial.o
  CC      net/netfilter/interceptor/ip_selector_db.o
  CC      net/netfilter/interceptor/ip_selector_match.o
  CC      drivers/usb/gadget/configfs.o
  CC      drivers/usb/notify/usb_notify.o
  LD      net/netfilter/netfilter.o
  CC      drivers/usb/phy/of.o
  LD      net/netfilter/nfnetlink_queue.o
  CC      drivers/usb/gadget/f_acm.o
  CC      net/netfilter/interceptor/kernelspd_main.o
  CC      net/netfilter/interceptor/kernelspd_hooks.o
  CC      net/netfilter/interceptor/kernelspd_procfs.o
  CC      drivers/usb/serial/generic.o
  CC      drivers/usb/phy/phy-samsung-usb.o
  CC      drivers/usb/host/xhci-hub.o
  CC      drivers/usb/serial/bus.o
  LD      net/netfilter/nf_conntrack.o
  CC      drivers/usb/gadget/u_serial.o
  CC      drivers/usb/gadget/multi_config.o
  CC      net/netfilter/interceptor/ipsec_boundary.o
  CC      drivers/usb/phy/phy-samsung-usb2-dummy.o
  CC      drivers/usb/serial/pl2303.o
  CC      net/netfilter/interceptor/debug_filter.o
  CC      drivers/usb/notify/usb_notify_sysfs.o
  CC      drivers/usb/notify/dock_notify.o
  CC      net/netfilter/interceptor/debug_strf.o
  CC      net/netfilter/interceptor/debug_linux.o
  LD      drivers/usb/serial/usbserial.o
  CC      drivers/usb/notify/usb_notifier.o
  CC      net/netfilter/interceptor/debug_strbuf_stack.o
  CC      drivers/usb/phy/phy-samsung-usb3.o
  CC      drivers/usb/phy/phy-samsung-usb3-cal.o
  LD      net/netfilter/interceptor/vpnclient.o
  LD      net/netfilter/interceptor/built-in.o
  LD      net/netfilter/built-in.o
  CC      net/unix/af_unix.o
  CC      drivers/usb/host/xhci-dbg.o
  CC      net/unix/garbage.o
  CC      net/unix/sysctl_net_unix.o
  LD      drivers/usb/notify/usb_notify_layer.o
  CC      drivers/usb/storage/scsiglue.o
  CC      drivers/usb/host/xhci-pci.o
  LD      drivers/usb/serial/built-in.o
  CC      drivers/usb/host/xhci-plat.o
  LD      drivers/usb/notify/built-in.o
  CC      drivers/usb/usb-common.o
  LD      drivers/usb/phy/built-in.o
  CC      net/wireless/core.o
  CC      drivers/usb/storage/protocol.o
  CC      drivers/usb/storage/transport.o
  CC      net/wireless/sysfs.o
  LD      drivers/usb/host/xhci-hcd.o
  LD      drivers/usb/host/built-in.o
  CC      net/wireless/radiotap.o
  CC      net/xfrm/xfrm_policy.o
  CC      net/wireless/util.o
  CC      net/compat.o
  CC      drivers/usb/storage/usb.o
  LD      drivers/usb/gadget/libcomposite.o
  LD      drivers/usb/gadget/usb_f_acm.o
  LD      drivers/usb/gadget/g_android.o
  LD      drivers/usb/gadget/built-in.o
  CC      drivers/usb/storage/initializers.o
  CC      net/wireless/reg.o
  CC      drivers/usb/storage/sierra_ms.o
  CC      net/wireless/scan.o
  CC      drivers/usb/storage/option_ms.o
  CC      drivers/usb/storage/usual-tables.o
  LD      net/unix/unix.o
  LD      net/unix/built-in.o
  CC      net/sysctl_net.o
  CC      net/activity_stats.o
  CC      net/xfrm/xfrm_state.o
  CC      net/wireless/nl80211.o
  CC      net/wireless/mlme.o
  LD      drivers/usb/storage/usb-storage.o
  LD      drivers/usb/storage/built-in.o
  LD      drivers/usb/built-in.o
Makefile:858: recipe for target 'drivers' failed
make: *** [drivers] Error 2
make: *** Waiting for unfinished jobs....
  CC      net/wireless/ibss.o
  CC      net/xfrm/xfrm_hash.o
  CC      net/wireless/sme.o
  CC      net/wireless/chan.o
  CC      net/xfrm/xfrm_input.o
  CC      net/wireless/ethtool.o
  CC      net/xfrm/xfrm_output.o
  CC      net/xfrm/xfrm_sysctl.o
  CC      net/wireless/mesh.o
  CC      net/wireless/ap.o
  CC      net/wireless/trace.o
  CC      net/wireless/wext-compat.o
  CC      net/xfrm/xfrm_replay.o
  CC      net/wireless/wext-sme.o
  CC      net/xfrm/xfrm_algo.o
  CC      net/wireless/wext-core.o
  CC      net/xfrm/xfrm_user.o
  CC      net/wireless/wext-proc.o
  CC      net/wireless/wext-priv.o
  CC      net/xfrm/xfrm_ipcomp.o
  LD      net/xfrm/built-in.o
  LD      net/wireless/cfg80211.o
  LD      net/wireless/built-in.o
  LD      net/built-in.o
Kernel STUCK in BUILD!
-------------------------------------------------------------------
What should I do? I have the HiD patch and the Driveroid Patch 

[Defconfig.zip](https://github.com/The-Sickness/S6-MM/files/1262050/Defconfig.zip)

This is based on the original exynos7420-zeroflte_defconfig
All patches are from Hybridmax

**Comment by The-Sickness** [comment]
First thing you need to do be adding commits is to build the stock source and make sure there are no compiling issues. Cause your errors is pointing at display issues.

**Comment by ghost** [comment]
Ok, Im going to try it that way thanks

**Comment by The-Sickness** [comment]
Always compile stock first to make sure there are no errors in the sources. It will save headaches later
